packages:
  - 'packages/*'
  - 'packages/internal/*'
  - 'examples/*'
  - 'packages/human'
  - 'packages/validation'
  - 'packages/testing'
  - 'packages/ops'
  - 'packages/importer'
  - 'packages/form'
  - 'packages/dmn'
